// AUTO-GENERATED by logos.py - do not edit by hand. Re-run logos.py after adding/removing files in img/logos/.
window.LOGO_TAGS = ["ctz", "godl", "ne", "ng", "rntx", "s8ul", "tag", "te", "tg", "tmr", "tp", "tsg"];
window.logoFile = function(tag) {
  var clean = String(tag).trim().replace(/[^a-zA-Z0-9_-]/g, "").toLowerCase();
  if (!clean || window.LOGO_TAGS.indexOf(clean) === -1) return null;
  return clean;
};
